---
env:
  es6: true
extends: airbnb
parser: babel-eslint
plugins:
- import
- prettier
rules:
  arrow-parens:
  - error
  - as-needed
  comma-dangle:
  - error
  - never
  quotes: off
  max-len: off
  no-use-before-define:
  - error
  - functions: false
  no-confusing-arrow: off
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  react/jsx-filename-extension: off
  react/forbid-prop-types: off
  prettier/prettier:
  - error
